export const cards = [
  'Jemand ist nicht vorbereitet/hat nicht aufgepasst',
  'Eine externe Person wird kontaktiert',
  'Der Name einer zuständigen Person wird gesucht',
  'Niemand weiß, wie etwas bestimmtes in der Ordnung geregelt ist',
  'Die Technik geht nicht',
  'Jemand kommt zu spät',
  'Platzhalter!',
  'Platzhalter!',
  'Platzhalter!',
  'Platzhalter!',
  'Eine Abstimmung/Wahl muss wiederholt werden',
  'Es wird im Protokoll gesprungen',
  'Etwas soll besser nicht protokolliert werden',
  '"Wie machen wir das jetzt?"',
  'Sitzungspause geht länger als gedacht',
  'Jemand häkelt',
  'Adde hat eine Idee',
  'Jemand vergisst einen GO-Antrag',
  'Nela muss eine Diskussion beenden',
  'Rahel fragt etwas fürs Protokoll nach',
  'Jemand geht früher',
  'Jemand liegt mit dem Kopf auf dem Tisch',
  'Eine Packung Katjes wird herumgegeben',
  'Eine Abkürzung muss erklärt werden',
  'Die Redeordnung wird nicht eingehalten',
];
