export const cards = [
  '...ChatGPT...',
  'Dann machen Sie was falsch!',
  'Erstellen Sie kein Modul-Info',
  'KLICKEN SIE NICHT',
  'Wiederstehen Sie dem Drang ...',
  'NICHT NICHT NICHT (Freifeld)',
  'Nutzen Sie Eclipse, dann funktioniert es auch!',
  'Keine Äs, keine Üs, keine SZs!',
  'Lassen Sie sich das von der IDE generieren!',
  'Kopieren Sie nichts, wenn Sie etwas kopieren, machen Sie etwas falsch!',
  'Wir brauchen keine KI dafür, das kann Ihre IDE schon ganz alleine!',
  'Clean Code Richtlinien!',
  'Was ist der Rückgabetyp des Konstruktors?',
  'Ich habe hier mal eine Umfrage vorbereitet, öffnen Sie die mal! (es funktioniert nicht)',
  '*flirtet mit Frau Geppert*',
  'Nutzen Sie Java11!',
  'syso Steuerung Leertaste',
  'ACHTUNG AUFGEPASST!!!',
  '*droppt random fact*',
  'Nochmal nach vorne gucken!',
  'Gute Programmierer haben maximal 30 Zeilen gleichzeitig auf dem Bildschirm!',
];
