export const cards = [
  'Rahel hebt einen Finger beim Reden',
  'Eine Person hat vergessen, was ein Amt macht',
  'Ein Meinungsbild wird angestimmt',
  'Mehr als 3 Leute melden sich für das Technik-Amt',
  'Ein Kopf liegt auf dem Tisch',
  'Wir überspringen Punkte im Protokoll',
  'Die Sitzung überschreitet 3 Stunden',
  'Eine Person fragt, ob etwas vegan ist',
  'Im Protokoll steht etwas lustiges',
  'Etwas wird in der Ordnung nachgeschaut',
  'Eine Sitzungspause wird gefordert',
  'Ein GO-Antrag wird vergessen',
  'Der Beamer verliert die Verbindung',
  'Niemand findet sich für ein Amt',
  'Eine Person muss früher gehen',
  'Eine Person kommt zu spät',
  'Ein Soundeffekt wird abgespielt',
  'Ein gewähltes Mitglied ist nicht anwesend',
  'Eine nicht gewählte Person stimmt mit ab',
  'Eine Person spricht, ohne sich zu melden',
  'Snacks werden herumgegeben',
  'Eine Diskussion dreht sich im Kreis',
  'Eine Wahl muss wiederholt werden',
  'Es wird sich über Technik beschwert',
  'Eine externe Person ist nicht anwesend',
];
