name: Build

run-name: Build Code

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build App
        run: |
          npm ci
          npm run build
          cd dist
          touch .nojekyll

      - name: Minify Code
        uses: Lenni009/minify-js@main
        with:
          directory: dist
          overwrite: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist

  deploy-main:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: artifact # The folder the action should deploy.

  deploy-branch:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name != 'main'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: artifact # The folder the action should deploy.
          target-folder: "${{ github.head_ref }}"
